const text = (de, en) => ({ de, en })

const studyQuestion = (number, group, topic, questionDe, questionEn, answerDe, answerEn) => ({
  id: `neck-${String(number).padStart(3, '0')}`,
  number,
  group,
  topic: text(topic.de, topic.en),
  question: text(questionDe, questionEn),
  answer: text(answerDe, answerEn),
})

export const neckGroups = [
  {
    id: 1,
    title: text('Grundlagen', 'Foundations'),
    description: text('Web, Layout und JavaScript-Grundlagen', 'Web, layout, and JavaScript foundations'),
    color: 'mint',
  },
  {
    id: 2,
    title: text('JavaScript & React', 'JavaScript & React'),
    description: text('Browser-Logik und React-Bausteine', 'Browser logic and React building blocks'),
    color: 'coral',
  },
  {
    id: 3,
    title: text('React & CSS', 'React & CSS'),
    description: text('Hooks, Routing, Semantik und Styling', 'Hooks, routing, semantics, and styling'),
    color: 'yellow',
  },
  {
    id: 4,
    title: text('Browser & Tooling', 'Browser & Tooling'),
    description: text('Speicher, Performance und Bereitstellung', 'Storage, performance, and deployment'),
    color: 'blue',
  },
  {
    id: 5,
    title: text('Architektur & Sicherheit', 'Architecture & Security'),
    description: text('React-Muster, Tests und Authentifizierung', 'React patterns, testing, and authentication'),
    color: 'violet',
  },
]

const topics = {
  networking: text('Networking', 'Networking'),
  http: text('HTTP', 'HTTP'),
  html: text('HTML & Accessibility', 'HTML & Accessibility'),
  css: text('CSS', 'CSS'),
  javascript: text('JavaScript', 'JavaScript'),
  browser: text('Browser APIs', 'Browser APIs'),
  security: text('Security', 'Security'),
  react: text('React', 'React'),
  tooling: text('Tooling & Deployment', 'Tooling & Deployment'),
  architecture: text('Architecture & Testing', 'Architecture & Testing'),
}

export const neckQuestions = [
  studyQuestion(1, 1, topics.networking,
    'Was ist ein Client im Web-Kontext?',
    'What is a client in a web context?',
    'Ein Programm, zum Beispiel ein Browser, das Anfragen an einen Server sendet.',
    'A program, such as a browser, that sends requests to a server.'),
  studyQuestion(2, 1, topics.networking,
    'Was ist 127.0.0.1?',
    'What is 127.0.0.1?',
    'Die Localhost- beziehungsweise Loopback-Adresse des eigenen Computers.',
    'The localhost or loopback address of your own computer.'),
  studyQuestion(3, 1, topics.networking,
    'Was macht DNS?',
    'What does DNS do?',
    'DNS löst Domainnamen in IP-Adressen auf.',
    'DNS resolves domain names into IP addresses.'),
  studyQuestion(4, 1, topics.http,
    'Was ist der Hauptunterschied zwischen HTTP und HTTPS?',
    'What is the main difference between HTTP and HTTPS?',
    'HTTPS verschlüsselt die Kommunikation mit TLS; HTTP überträgt sie unverschlüsselt.',
    'HTTPS encrypts communication using TLS; HTTP sends it without that encryption.'),
  studyQuestion(5, 1, topics.http,
    'Welche HTTP-Methoden werden typischerweise für CRUD verwendet?',
    'Which HTTP methods are commonly used for CRUD?',
    'GET zum Lesen, POST zum Erstellen, PUT oder PATCH zum Aktualisieren und DELETE zum Löschen.',
    'GET for reading, POST for creating, PUT or PATCH for updating, and DELETE for deleting.'),
  studyQuestion(6, 1, topics.http,
    'Welche Statuscodes zeigen einen erfolgreichen Request an?',
    'Which status codes indicate a successful request?',
    'Statuscodes aus dem 2xx-Bereich, zum Beispiel 200 und 201.',
    '2xx status codes, such as 200 and 201.'),
  studyQuestion(7, 1, topics.html,
    'Wozu dient das alt-Attribut?',
    'What does the alt attribute do?',
    'Es stellt eine Textbeschreibung eines Bildes für Barrierefreiheit und Fallback-Situationen bereit.',
    'It provides a text description of an image for accessibility and fallback situations.'),
  studyQuestion(8, 1, topics.css,
    'Was bewirkt box-sizing: border-box?',
    'What does box-sizing: border-box do?',
    'Padding und Border werden in die angegebene Breite und Höhe eines Elements eingerechnet.',
    'Padding and border are included in the element’s declared width and height.'),
  studyQuestion(9, 1, topics.css,
    'Wofür eignet sich Flexbox am besten?',
    'What is Flexbox best used for?',
    'Für eindimensionale Layouts entlang einer Zeile oder einer Spalte.',
    'For one-dimensional layouts along a row or a column.'),
  studyQuestion(10, 1, topics.css,
    'Wofür eignet sich CSS Grid am besten?',
    'What is CSS Grid best used for?',
    'Für zweidimensionale Layouts mit Zeilen und Spalten.',
    'For two-dimensional layouts with rows and columns.'),
  studyQuestion(11, 1, topics.html,
    'Wie macht man HTML-Formulare zugänglich?',
    'How do you make HTML forms accessible?',
    'Eingaben brauchen verständliche Labels, eine logische Tastaturreihenfolge, klare Fehlermeldungen und passende native Formularelemente.',
    'Inputs need clear labels, a logical keyboard order, understandable errors, and appropriate native form elements.'),
  studyQuestion(12, 1, topics.css,
    'Wozu dienen Media Queries im Responsive Design?',
    'What are media queries used for in responsive design?',
    'Sie wenden CSS-Regeln abhängig von Eigenschaften wie Bildschirmbreite oder Orientierung an.',
    'They apply CSS rules based on characteristics such as screen width or orientation.'),
  studyQuestion(13, 1, topics.javascript,
    'Welche Werte gelten in JavaScript als falsy?',
    'Which values are falsy in JavaScript?',
    'false, 0, -0, 0n, ein leerer String, null, undefined und NaN.',
    'false, 0, -0, 0n, an empty string, null, undefined, and NaN.'),

  studyQuestion(14, 1, topics.javascript,
    'Was ist der Unterschied zwischen null und undefined?',
    'What is the difference between null and undefined?',
    'null wird meist bewusst als leerer Wert gesetzt; undefined bedeutet gewöhnlich, dass noch kein Wert vorhanden oder zugewiesen ist.',
    'null is usually an intentionally empty value; undefined normally means no value is present or assigned yet.'),
  studyQuestion(15, 1, topics.javascript,
    'Was macht der Nullish-Coalescing-Operator ??',
    'What does the nullish coalescing operator ?? do?',
    'Er verwendet den rechten Wert nur dann als Fallback, wenn der linke Wert null oder undefined ist.',
    'It uses the right-hand value as a fallback only when the left-hand value is null or undefined.'),
  studyQuestion(16, 1, topics.javascript,
    'Was macht die Array-Methode map()?',
    'What does the array method map() do?',
    'Sie erzeugt ein neues Array, indem eine Funktion auf jedes Element des ursprünglichen Arrays angewendet wird.',
    'It creates a new array by applying a function to every element of the original array.'),
  studyQuestion(17, 1, topics.browser,
    'Was bedeutet DOM-Manipulation?',
    'What is DOM manipulation?',
    'Das Lesen, Erstellen, Ändern oder Entfernen von Elementen und Inhalten der Dokumentstruktur mit JavaScript.',
    'Reading, creating, changing, or removing elements and content in the document structure with JavaScript.'),
  studyQuestion(18, 1, topics.javascript,
    'Was ist JSON?',
    'What is JSON?',
    'Ein textbasiertes Datenformat für strukturierte Daten, das häufig zwischen Client und Server übertragen wird.',
    'A text-based format for structured data that is commonly exchanged between client and server.'),
  studyQuestion(19, 1, topics.http,
    'Was ist eine Web-API?',
    'What is a web API?',
    'Eine definierte Schnittstelle, über die Anwendungen per Requests Daten oder Funktionen austauschen.',
    'A defined interface through which applications exchange data or functionality using requests.'),
  studyQuestion(20, 1, topics.javascript,
    'Wozu dienen async und await?',
    'What are async and await used for?',
    'Sie machen Promise-basierten asynchronen Code leichter lesbar und ermöglichen das Warten auf ein Ergebnis innerhalb einer async-Funktion.',
    'They make Promise-based asynchronous code easier to read and let an async function wait for a result.'),
  studyQuestion(21, 2, topics.javascript,
    'Wie behandelt man Fehler in JavaScript?',
    'How do you handle errors in JavaScript?',
    'Mit try/catch, sinnvoller Validierung, Promise-Fehlerbehandlung und verständlichen Fehlermeldungen.',
    'With try/catch, meaningful validation, Promise error handling, and understandable error messages.'),
  studyQuestion(22, 2, topics.browser,
    'Wofür nutzt man Browser Developer Tools?',
    'What are browser developer tools used for?',
    'Zum Untersuchen von HTML und CSS, Debuggen von JavaScript, Prüfen von Requests sowie Analysieren von Performance und Speicher.',
    'To inspect HTML and CSS, debug JavaScript, examine requests, and analyze performance and memory.'),
  studyQuestion(23, 2, topics.security,
    'Was ist Cross-Site Scripting (XSS)?',
    'What is cross-site scripting (XSS)?',
    'Eine Sicherheitslücke, bei der nicht vertrauenswürdiger Inhalt als Skript in einer Webseite ausgeführt wird.',
    'A vulnerability in which untrusted content is executed as a script inside a web page.'),
  studyQuestion(24, 2, topics.react,
    'Was ist eine React-Komponente?',
    'What is a React component?',
    'Eine wiederverwendbare UI-Einheit, die aus Daten und Zustand eine Darstellung erzeugt.',
    'A reusable UI unit that produces a view from data and state.'),
  studyQuestion(25, 2, topics.react,
    'Was sind Props in React?',
    'What are props in React?',
    'Schreibgeschützte Eingabewerte, die eine Elternkomponente an eine Kindkomponente übergibt.',
    'Read-only input values passed from a parent component to a child component.'),
  studyQuestion(26, 2, topics.react,
    'Was bedeutet State in React?',
    'What does state mean in React?',
    'Veränderliche Daten einer Komponente, deren Aktualisierung ein erneutes Rendern auslösen kann.',
    'Changeable component data whose update can trigger a re-render.'),

  studyQuestion(27, 2, topics.react,
    'Wozu dient der React Hook useState?',
    'What is the React useState hook used for?',
    'Er fügt einer Funktionskomponente lokalen Zustand und eine Funktion zum Aktualisieren dieses Zustands hinzu.',
    'It adds local state and a state-update function to a function component.'),
  studyQuestion(28, 2, topics.react,
    'Wozu dient useEffect?',
    'What is useEffect used for?',
    'Zum Synchronisieren einer Komponente mit externen Systemen, etwa Requests, Events oder Browser-APIs.',
    'To synchronize a component with external systems such as requests, events, or browser APIs.'),
  studyQuestion(29, 2, topics.react,
    'Was ist eine kontrollierte Komponente in React?',
    'What is a controlled component in React?',
    'Ein Formularelement, dessen aktueller Wert durch React State gesteuert und über einen Event Handler aktualisiert wird.',
    'A form element whose value is controlled by React state and updated through an event handler.'),
  studyQuestion(30, 2, topics.react,
    'Wozu dient React Router?',
    'What is React Router used for?',
    'Zum Zuordnen von URLs zu UI-Ansichten und für clientseitige Navigation in React-Anwendungen.',
    'To map URLs to UI views and provide client-side navigation in React applications.'),
  studyQuestion(31, 2, topics.react,
    'Was macht React.memo?',
    'What does React.memo do?',
    'Es kann unnötige erneute Renderings einer Komponente vermeiden, wenn sich ihre Props nicht geändert haben.',
    'It can avoid unnecessary component re-renders when its props have not changed.'),
  studyQuestion(32, 2, topics.html,
    'Was ist semantisches HTML?',
    'What is semantic HTML?',
    'HTML, dessen Elemente die Bedeutung und Rolle ihres Inhalts beschreiben, zum Beispiel main, nav oder article.',
    'HTML whose elements describe the meaning and role of their content, such as main, nav, or article.'),
  studyQuestion(33, 2, topics.css,
    'Was bedeutet CSS-Spezifität?',
    'What does CSS specificity mean?',
    'Ein Gewichtungssystem, das mitbestimmt, welche konkurrierende CSS-Regel auf ein Element angewendet wird.',
    'A weighting system that helps determine which competing CSS rule is applied to an element.'),
  studyQuestion(34, 2, topics.css,
    'Welche wichtigen position-Werte gibt es in CSS?',
    'What are the important CSS position values?',
    'static, relative, absolute, fixed und sticky; sie bestimmen, wie ein Element positioniert und aus dem normalen Fluss gelöst wird.',
    'static, relative, absolute, fixed, and sticky; they determine how an element is positioned and removed from normal flow.'),
  studyQuestion(35, 2, topics.css,
    'Wofür wird z-index verwendet?',
    'What is z-index used for?',
    'Er beeinflusst die Stapelreihenfolge positionierter Elemente innerhalb ihrer Stacking Contexts.',
    'It affects the stacking order of positioned elements within their stacking contexts.'),
  studyQuestion(36, 2, topics.css,
    'Wie funktionieren CSS-Animationen?',
    'How do CSS animations work?',
    'Keyframes definieren Zwischenzustände; animation-Eigenschaften steuern Name, Dauer, Timing und Wiederholung.',
    'Keyframes define intermediate states; animation properties control the name, duration, timing, and repetition.'),
  studyQuestion(37, 2, topics.javascript,
    'Warum verwendet man Funktionen?',
    'Why are functions used?',
    'Sie kapseln wiederverwendbare Logik, nehmen Eingaben entgegen und können Ergebnisse zurückgeben.',
    'They encapsulate reusable logic, accept inputs, and can return results.'),
  studyQuestion(38, 2, topics.javascript,
    'Was ist eine Arrow Function?',
    'What is an arrow function?',
    'Eine kompakte Funktionssyntax mit lexikalischem this, geschrieben zum Beispiel als const add = (a, b) => a + b.',
    'A compact function syntax with lexical this, for example const add = (a, b) => a + b.'),
  studyQuestion(39, 2, topics.javascript,
    'Was bedeutet Scope in JavaScript?',
    'What does scope mean in JavaScript?',
    'Der Bereich, in dem eine Variable oder Funktion sichtbar und zugänglich ist.',
    'The region in which a variable or function is visible and accessible.'),

  studyQuestion(40, 2, topics.javascript,
    'Was bedeutet Hoisting in JavaScript?',
    'What does hoisting mean in JavaScript?',
    'Deklarationen werden bei der Verarbeitung ihres Scopes vor der Ausführung registriert; ihr tatsächliches Verhalten hängt von var, let, const oder function ab.',
    'Declarations are registered when their scope is processed before execution; the exact behavior depends on var, let, const, or function.'),
  studyQuestion(41, 3, topics.javascript,
    'Was liefert Object.keys()?',
    'What does Object.keys() return?',
    'Ein Array mit den eigenen aufzählbaren Property-Namen eines Objekts.',
    'An array containing an object’s own enumerable property names.'),
  studyQuestion(42, 3, topics.javascript,
    'Was macht Optional Chaining mit ?.',
    'What does optional chaining with ?. do?',
    'Es greift sicher auf verschachtelte Properties oder Methoden zu und liefert undefined, wenn ein früher Teil null oder undefined ist.',
    'It safely accesses nested properties or methods and returns undefined if an earlier part is null or undefined.'),
  studyQuestion(43, 3, topics.browser,
    'Was macht addEventListener()?',
    'What does addEventListener() do?',
    'Es registriert eine Funktion, die ausgeführt wird, wenn ein bestimmtes Event auf einem Ziel eintritt.',
    'It registers a function to run when a specific event occurs on a target.'),
  studyQuestion(44, 3, topics.browser,
    'Was ist localStorage?',
    'What is localStorage?',
    'Ein Browser-Speicher für String-Daten, die für dieselbe Origin auch nach dem Schließen des Browsers erhalten bleiben.',
    'Browser storage for string data that remains available to the same origin after the browser is closed.'),
  studyQuestion(45, 3, topics.browser,
    'Was ist sessionStorage?',
    'What is sessionStorage?',
    'Ein Browser-Speicher pro Tab beziehungsweise Sitzung, der beim Schließen des Tabs gelöscht wird.',
    'Browser storage scoped to a tab or session that is cleared when the tab is closed.'),
  studyQuestion(46, 3, topics.browser,
    'Was sind Cookies?',
    'What are cookies?',
    'Kleine Schlüssel-Wert-Daten, die der Browser speichert und bei passenden HTTP-Requests an den Server mitsenden kann.',
    'Small key-value data stored by the browser that can be sent to the server with matching HTTP requests.'),
  studyQuestion(47, 3, topics.http,
    'Was ist CORS?',
    'What is CORS?',
    'Ein Browser-Sicherheitsmechanismus, bei dem Server über HTTP-Header erlaubte Cross-Origin-Zugriffe festlegen.',
    'A browser security mechanism in which servers use HTTP headers to allow selected cross-origin access.'),
  studyQuestion(48, 3, topics.browser,
    'Wie verbessert man die Performance einer Webseite?',
    'How can website performance be improved?',
    'Durch kleinere Assets, weniger JavaScript, Caching, Lazy Loading, effizientes Rendering und das Messen realer Engpässe.',
    'By reducing asset size and JavaScript, using caching and lazy loading, rendering efficiently, and measuring real bottlenecks.'),
  studyQuestion(49, 3, topics.browser,
    'Was bedeutet Rendering im Browser?',
    'What does rendering mean in the browser?',
    'Der Prozess, bei dem DOM und CSSOM zu Layout, Pixeln und der sichtbaren Webseite verarbeitet werden.',
    'The process of turning the DOM and CSSOM into layout, pixels, and the visible page.'),
  studyQuestion(50, 3, topics.tooling,
    'Was ist npm?',
    'What is npm?',
    'Ein Paketmanager und Registry-Ökosystem für JavaScript-Abhängigkeiten und Projektskripte.',
    'A package manager and registry ecosystem for JavaScript dependencies and project scripts.'),
  studyQuestion(51, 3, topics.tooling,
    'Was passiert in einem Frontend-Build-Prozess?',
    'What happens during a frontend build process?',
    'Quellcode und Assets werden geprüft, transformiert, gebündelt und für die Auslieferung optimiert.',
    'Source code and assets are checked, transformed, bundled, and optimized for delivery.'),
  studyQuestion(52, 3, topics.tooling,
    'Was bedeutet Deployment?',
    'What does deployment mean?',
    'Eine gebaute Anwendung wird in eine Umgebung veröffentlicht, in der Nutzer sie erreichen können.',
    'A built application is published to an environment where users can access it.'),

  studyQuestion(53, 3, topics.react,
    'Was ist JSX?',
    'What is JSX?',
    'Eine JavaScript-Syntaxerweiterung, mit der UI-Strukturen ähnlich wie HTML im Code beschrieben werden.',
    'A JavaScript syntax extension for describing UI structures in a form similar to HTML.'),
  studyQuestion(54, 3, topics.react,
    'Warum brauchen Listenelemente in React einen key?',
    'Why do list items in React need a key?',
    'Ein stabiler key hilft React, Elemente zwischen Renderings korrekt zuzuordnen und effizient zu aktualisieren.',
    'A stable key helps React match items between renders and update them efficiently.'),
  studyQuestion(55, 3, topics.react,
    'Was ist Conditional Rendering?',
    'What is conditional rendering?',
    'Das Anzeigen unterschiedlicher UI abhängig von Zustand oder Bedingungen, etwa mit if, && oder dem ternären Operator.',
    'Showing different UI based on state or conditions, using if, &&, or the ternary operator.'),
  studyQuestion(56, 3, topics.react,
    'Wozu dient useRef?',
    'What is useRef used for?',
    'Zum Speichern eines veränderlichen Werts ohne Re-Render oder zum Referenzieren eines DOM-Elements.',
    'To store a mutable value without re-rendering or to reference a DOM element.'),
  studyQuestion(57, 3, topics.react,
    'Wozu dient React Context?',
    'What is React Context used for?',
    'Zum Bereitstellen gemeinsamer Werte für einen Komponentenbaum, ohne Props durch jede Zwischenebene weiterzureichen.',
    'To provide shared values to a component tree without passing props through every intermediate level.'),
  studyQuestion(58, 3, topics.http,
    'Was macht fetch()?',
    'What does fetch() do?',
    'fetch() startet einen HTTP-Request und liefert ein Promise mit einem Response-Objekt.',
    'fetch() starts an HTTP request and returns a Promise containing a Response object.'),
  studyQuestion(59, 3, topics.react,
    'Was ist clientseitiges Routing?',
    'What is client-side routing?',
    'Die URL und Ansicht wechseln im Browser, ohne bei jeder Navigation ein vollständiges neues HTML-Dokument zu laden.',
    'The URL and view change in the browser without loading a complete new HTML document for every navigation.'),
  studyQuestion(60, 3, topics.architecture,
    'Welche Arten von Tests sind in Webanwendungen wichtig?',
    'Which kinds of tests are important in web applications?',
    'Unit-Tests prüfen kleine Einheiten, Integrationstests ihr Zusammenspiel und End-to-End-Tests vollständige Nutzerabläufe.',
    'Unit tests check small units, integration tests check how they work together, and end-to-end tests check complete user flows.'),
  studyQuestion(61, 4, topics.architecture,
    'Was bedeutet Single Source of Truth?',
    'What does single source of truth mean?',
    'Eine Information wird an einer maßgeblichen Stelle verwaltet, statt in mehreren unabhängigen Kopien.',
    'A piece of information is managed in one authoritative place instead of several independent copies.'),
  studyQuestion(62, 4, topics.architecture,
    'Was zeichnet eine gute Projektordnerstruktur aus?',
    'What makes a good project folder structure?',
    'Sie gruppiert zusammengehörige Dateien nachvollziehbar, hält Verantwortlichkeiten klar und bleibt bei wachsendem Projekt auffindbar.',
    'It groups related files predictably, keeps responsibilities clear, and remains navigable as the project grows.'),
  studyQuestion(63, 4, topics.security,
    'Was ist Authentifizierung?',
    'What is authentication?',
    'Der Prozess, mit dem überprüft wird, wer ein Nutzer oder eine Anwendung ist.',
    'The process of verifying who a user or application is.'),
  studyQuestion(64, 4, topics.security,
    'Was ist Multi-Faktor-Authentifizierung (MFA)?',
    'What is multi-factor authentication (MFA)?',
    'Eine Anmeldung mit mindestens zwei unterschiedlichen Nachweisarten, etwa Passwort und Einmalcode.',
    'A sign-in that requires at least two different types of proof, such as a password and a one-time code.'),
  studyQuestion(65, 4, topics.http,
    'Wie läuft ein typischer Request-Response-Zyklus ab?',
    'How does a typical request-response cycle work?',
    'Ein Client sendet einen Request, der Server verarbeitet ihn und sendet eine Response mit Status, Headern und optionalen Daten zurück.',
    'A client sends a request, the server processes it, and returns a response with a status, headers, and optional data.'),
]

export const getNeckGroupQuestions = (groupId) =>
  neckQuestions.filter((item) => item.group === Number(groupId))

export const getNeckQuestionById = (id) =>
  neckQuestions.find((item) => item.id === id)
