const text = (de, en) => ({ de, en })

const distractors = [
  text('Eine CSS-Regel', 'A CSS rule'),
  text('Ein Browser-Event', 'A browser event'),
  text('Ein HTML-Struktur', 'An HTML structure'),
  text('Ein JavaScript-Objekt', 'A JavaScript object'),
  text('Ein Netzwerkprotokoll', 'A network protocol'),
  text('Ein Datenbankeintrag', 'A database entry'),
  text('Eine Route', 'A route'),
  text('Ein Formularfeld', 'A form field'),
  text('Ein Authentifizierungsfaktor', 'An authentication factor'),
  text('Ein Speichermedium', 'A storage medium'),
  text('Ein Dateiformat', 'A file format'),
  text('Ein Webseiten-Layout', 'A website layout'),
  text('Ein Bildformat', 'An image format'),
  text('Eine Benutzerrolle', 'A user role'),
]

const stableShuffle = (items, seed) => {
  const copy = [...items]
  for (let i = copy.length - 1; i > 0; i -= 1) {
    const j = (seed + i * 37) % (i + 1)
    ;[copy[i], copy[j]] = [copy[j], copy[i]]
  }
  return copy
}

const createOptions = (answer, number) => {
  const candidates = distractors.filter(
    (item) => item.de !== answer.de && item.en !== answer.en,
  )
  const options = [answer]
  let index = number % candidates.length

  while (options.length < 3 && options.length < candidates.length) {
    const candidate = candidates[index]
    if (!options.some((item) => item.de === candidate.de && item.en === candidate.en)) {
      options.push(candidate)
    }
    index = (index + 1) % candidates.length
  }

  return stableShuffle(options, number)
}

const studyQuestion = (
  number,
  group,
  topic,
  questionDe,
  questionEn,
  answerDe,
  answerEn,
) => {
  const answer = text(answerDe, answerEn)
  const options = createOptions(answer, number)
  return {
    id: `neck-${String(number).padStart(3, '0')}`,
    number,
    group,
    topic: text(topic.de, topic.en),
    question: text(questionDe, questionEn),
    answer,
    options,
    correct: options.findIndex(
      (option) => option.de === answer.de && option.en === answer.en,
    ),
  }
}

export const neckGroups = [
  {
    id: 1,
    title: text('Grundlagen', 'Foundations'),
    description: text('Web, Layout und JavaScript-Grundlagen', 'Web, layout, and JavaScript foundations'),
    color: 'mint',
  },
  {
    id: 2,
    title: text('JavaScript & React', 'JavaScript & React'),
    description: text('Browser-Logik und React-Bausteine', 'Browser logic and React building blocks'),
    color: 'coral',
  },
  {
    id: 3,
    title: text('React & CSS', 'React & CSS'),
    description: text('Hooks, Routing, Semantik und Styling', 'Hooks, routing, semantics, and styling'),
    color: 'yellow',
  },
  {
    id: 4,
    title: text('Browser & Tooling', 'Browser & Tooling'),
    description: text('Speicher, Performance und Bereitstellung', 'Storage, performance, and deployment'),
    color: 'blue',
  },
  {
    id: 5,
    title: text('Architektur & Sicherheit', 'Architecture & Security'),
    description: text('React-Muster, Tests und Authentifizierung', 'React patterns, testing, and authentication'),
    color: 'violet',
  },
]

const topics = {
  networking: text('Networking', 'Networking'),
  http: text('HTTP', 'HTTP'),
  html: text('HTML & Accessibility', 'HTML & Accessibility'),
  css: text('CSS', 'CSS'),
  javascript: text('JavaScript', 'JavaScript'),
  browser: text('Browser APIs', 'Browser APIs'),
  security: text('Security', 'Security'),
  react: text('React', 'React'),
  tooling: text('Tooling & Deployment', 'Tooling & Deployment'),
  architecture: text('Architecture & Testing', 'Architecture & Testing'),
}

export const neckQuestions = [
  studyQuestion(1, 1, topics.networking,
    'Was ist ein Client im Web-Kontext?',
    'What is a client in a web context?',
    'Ein Programm, zum Beispiel ein Browser, das Anfragen an einen Server sendet.',
    'A program, such as a browser, that sends requests to a server.'),
  studyQuestion(2, 1, topics.networking,
    'Was ist 127.0.0.1?',
    'What is 127.0.0.1?',
    'Die Localhost- beziehungsweise Loopback-Adresse des eigenen Computers.',
    'The localhost or loopback address of your own computer.'),
  studyQuestion(3, 1, topics.networking,
    'Was macht DNS?',
    'What does DNS do?',
    'DNS löst Domainnamen in IP-Adressen auf.',
    'DNS resolves domain names into IP addresses.'),
  studyQuestion(4, 1, topics.http,
    'Was ist der Hauptunterschied zwischen HTTP und HTTPS?',
    'What is the main difference between HTTP and HTTPS?',
    'HTTPS verschlüsselt die Kommunikation mit TLS; HTTP überträgt sie unverschlüsselt.',
    'HTTPS encrypts communication using TLS; HTTP sends it without that encryption.'),
  studyQuestion(5, 1, topics.http,
    'Welche HTTP-Methoden werden typischerweise für CRUD verwendet?',
    'Which HTTP methods are commonly used for CRUD?',
    'GET zum Lesen, POST zum Erstellen, PUT oder PATCH zum Aktualisieren und DELETE zum Löschen.',
    'GET for reading, POST for creating, PUT or PATCH for updating, and DELETE for deleting.'),
  studyQuestion(6, 1, topics.http,
    'Welche Statuscodes zeigen einen erfolgreichen Request an?',
    'Which status codes indicate a successful request?',
    'Statuscodes aus dem 2xx-Bereich, zum Beispiel 200 und 201.',
    '2xx status codes, such as 200 and 201.'),
  studyQuestion(7, 1, topics.html,
    'Wozu dient das alt-Attribut?',
    'What does the alt attribute do?',
    'Es stellt eine Textbeschreibung eines Bildes für Barrierefreiheit und Fallback-Situationen bereit.',
    'It provides a text description of an image for accessibility and fallback situations.'),
  studyQuestion(8, 1, topics.css,
    'Was bewirkt box-sizing: border-box?',
    'What does box-sizing: border-box do?',
    'Padding und Border werden in die angegebene Breite und Höhe eines Elements eingerechnet.',
    'Padding and border are included in the element’s declared width and height.'),
  studyQuestion(9, 1, topics.css,
    'Wofür eignet sich Flexbox am besten?',
    'What is Flexbox best used for?',
    'Für eindimensionale Layouts entlang einer Zeile oder einer Spalte.',
    'For one-dimensional layouts along a row or a column.'),
  studyQuestion(10, 1, topics.css,
    'Wofür eignet sich CSS Grid am besten?',
    'What is CSS Grid best used for?',
    'Für zweidimensionale Layouts mit Zeilen und Spalten.',
    'For two-dimensional layouts with rows and columns.'),
  studyQuestion(11, 1, topics.html,
    'Wie macht man HTML-Formulare zugänglich?',
    'How do you make HTML forms accessible?',
    'Eingaben brauchen verständliche Labels, eine logische Tastaturreihenfolge, klare Fehlermeldungen und passende native Formularelemente.',
    'Inputs need clear labels, a logical keyboard order, understandable errors, and appropriate native form elements.'),
  studyQuestion(12, 1, topics.css,
    'Wozu dienen Media Queries im Responsive Design?',
    'What are media queries used for in responsive design?',
    'Sie wenden CSS-Regeln abhängig von Eigenschaften wie Bildschirmbreite oder Orientierung an.',
    'They apply CSS rules based on characteristics such as screen width or orientation.'),
  studyQuestion(13, 1, topics.javascript,
    'Welche Werte gelten in JavaScript als falsy?',
    'Which values are falsy in JavaScript?',
    'false, 0, -0, 0n, ein leerer String, null, undefined und NaN.',
    'false, 0, -0, 0n, an empty string, null, undefined, and NaN.'),

  studyQuestion(14, 1, topics.javascript,
    'Was ist der Unterschied zwischen null und undefined?',
    'What is the difference between null and undefined?',
    'null wird meist bewusst als leerer Wert gesetzt; undefined bedeutet gewöhnlich, dass noch kein Wert vorhanden oder zugewiesen ist.',
    'null is usually an intentionally empty value; undefined normally means no value is present or assigned yet.'),
  studyQuestion(15, 1, topics.javascript,
    'Was macht der Nullish-Coalescing-Operator ??',
    'What does the nullish coalescing operator ?? do?',
    'Er verwendet den rechten Wert nur dann als Fallback, wenn der linke Wert null oder undefined ist.',
    'It uses the right-hand value as a fallback only when the left-hand value is null or undefined.'),
  studyQuestion(16, 1, topics.javascript,
    'Was macht die Array-Methode map()?',
    'What does the array method map() do?',
    'Sie erzeugt ein neues Array, indem eine Funktion auf jedes Element des ursprünglichen Arrays angewendet wird.',
    'It creates a new array by applying a function to every element of the original array.'),
  studyQuestion(17, 1, topics.browser,
    'Was bedeutet DOM-Manipulation?',
    'What is DOM manipulation?',
    'Das Lesen, Erstellen, Ändern oder Entfernen von Elementen und Inhalten der Dokumentstruktur mit JavaScript.',
    'Reading, creating, changing, or removing elements and content in the document structure with JavaScript.'),
  studyQuestion(18, 1, topics.javascript,
    'Was ist JSON?',
    'What is JSON?',
    'Ein textbasiertes Datenformat für strukturierte Daten, das häufig zwischen Client und Server übertragen wird.',
    'A text-based format for structured data that is commonly exchanged between client and server.'),
  studyQuestion(19, 1, topics.http,
    'Was ist eine Web-API?',
    'What is a web API?',
    'Eine definierte Schnittstelle, über die Anwendungen per Requests Daten oder Funktionen austauschen.',
    'A defined interface through which applications exchange data or functionality using requests.'),
  studyQuestion(20, 1, topics.javascript,
    'Wozu dienen async und await?',
    'What are async and await used for?',
    'Sie machen Promise-basierten asynchronen Code leichter lesbar und ermöglichen das Warten auf ein Ergebnis innerhalb einer async-Funktion.',
    'They make Promise-based asynchronous code easier to read and let an async function wait for a result.'),
  studyQuestion(21, 2, topics.javascript,
    'Wie behandelt man Fehler in JavaScript?',
    'How do you handle errors in JavaScript?',
    'Mit try/catch, sinnvoller Validierung, Promise-Fehlerbehandlung und verständlichen Fehlermeldungen.',
    'With try/catch, meaningful validation, Promise error handling, and understandable error messages.'),
  studyQuestion(22, 2, topics.browser,
    'Wofür nutzt man Browser Developer Tools?',
    'What are browser developer tools used for?',
    'Zum Untersuchen von HTML und CSS, Debuggen von JavaScript, Prüfen von Requests sowie Analysieren von Performance und Speicher.',
    'To inspect HTML and CSS, debug JavaScript, examine requests, and analyze performance and memory.'),
  studyQuestion(23, 2, topics.security,
    'Was ist Cross-Site Scripting (XSS)?',
    'What is cross-site scripting (XSS)?',
    'Eine Sicherheitslücke, bei der nicht vertrauenswürdiger Inhalt als Skript in einer Webseite ausgeführt wird.',
    'A vulnerability in which untrusted content is executed as a script inside a web page.'),
  studyQuestion(24, 2, topics.react,
    'Was ist eine React-Komponente?',
    'What is a React component?',
    'Eine wiederverwendbare UI-Einheit, die aus Daten und Zustand eine Darstellung erzeugt.',
    'A reusable UI unit that produces a view from data and state.'),
  studyQuestion(25, 2, topics.react,
    'Was sind Props in React?',
    'What are props in React?',
    'Schreibgeschützte Eingabewerte, die eine Elternkomponente an eine Kindkomponente übergibt.',
    'Read-only input values passed from a parent component to a child component.'),
  studyQuestion(26, 2, topics.react,
    'Was bedeutet State in React?',
    'What does state mean in React?',
    'Veränderliche Daten einer Komponente, deren Aktualisierung ein erneutes Rendern auslösen kann.',
    'Changeable component data whose update can trigger a re-render.'),

  studyQuestion(27, 2, topics.react,
    'Wozu dient der React Hook useState?',
    'What is the React useState hook used for?',
    'Er fügt einer Funktionskomponente lokalen Zustand und eine Funktion zum Aktualisieren dieses Zustands hinzu.',
    'It adds local state and a state-update function to a function component.'),
  studyQuestion(28, 2, topics.react,
    'Wozu dient useEffect?',
    'What is useEffect used for?',
    'Zum Synchronisieren einer Komponente mit externen Systemen, etwa Requests, Events oder Browser-APIs.',
    'To synchronize a component with external systems such as requests, events, or browser APIs.'),
  studyQuestion(29, 2, topics.react,
    'Was ist eine kontrollierte Komponente in React?',
    'What is a controlled component in React?',
    'Ein Formularelement, dessen aktueller Wert durch React State gesteuert und über einen Event Handler aktualisiert wird.',
    'A form element whose value is controlled by React state and updated through an event handler.'),
  studyQuestion(30, 2, topics.react,
    'Wozu dient React Router?',
    'What is React Router used for?',
    'Zum Zuordnen von URLs zu UI-Ansichten und für clientseitige Navigation in React-Anwendungen.',
    'To map URLs to UI views and provide client-side navigation in React applications.'),
  studyQuestion(31, 2, topics.react,
    'Was macht React.memo?',
    'What does React.memo do?',
    'Es kann unnötige erneute Renderings einer Komponente vermeiden, wenn sich ihre Props nicht geändert haben.',
    'It can avoid unnecessary component re-renders when its props have not changed.'),
  studyQuestion(32, 2, topics.html,
    'Was ist semantisches HTML?',
    'What is semantic HTML?',
    'HTML, dessen Elemente die Bedeutung und Rolle ihres Inhalts beschreiben, zum Beispiel main, nav oder article.',
    'HTML whose elements describe the meaning and role of their content, such as main, nav, or article.'),
  studyQuestion(33, 2, topics.css,
    'Was bedeutet CSS-Spezifität?',
    'What does CSS specificity mean?',
    'Ein Gewichtungssystem, das mitbestimmt, welche konkurrierende CSS-Regel auf ein Element angewendet wird.',
    'A weighting system that helps determine which competing CSS rule is applied to an element.'),
  studyQuestion(34, 2, topics.css,
    'Welche wichtigen position-Werte gibt es in CSS?',
    'What are the important CSS position values?',
    'static, relative, absolute, fixed und sticky; sie bestimmen, wie ein Element positioniert und aus dem normalen Fluss gelöst wird.',
    'static, relative, absolute, fixed, and sticky; they determine how an element is positioned and removed from normal flow.'),
  studyQuestion(35, 2, topics.css,
    'Wofür wird z-index verwendet?',
    'What is z-index used for?',
    'Er beeinflusst die Stapelreihenfolge positionierter Elemente innerhalb ihrer Stacking Contexts.',
    'It affects the stacking order of positioned elements within their stacking contexts.'),
  studyQuestion(36, 2, topics.css,
    'Wie funktionieren CSS-Animationen?',
    'How do CSS animations work?',
    'Keyframes definieren Zwischenzustände; animation-Eigenschaften steuern Name, Dauer, Timing und Wiederholung.',
    'Keyframes define intermediate states; animation properties control the name, duration, timing, and repetition.'),
  studyQuestion(37, 2, topics.javascript,
    'Warum verwendet man Funktionen?',
    'Why are functions used?',
    'Sie kapseln wiederverwendbare Logik, nehmen Eingaben entgegen und können Ergebnisse zurückgeben.',
    'They encapsulate reusable logic, accept inputs, and can return results.'),
  studyQuestion(38, 2, topics.javascript,
    'Was ist eine Arrow Function?',
    'What is an arrow function?',
    'Eine kompakte Funktionssyntax mit lexikalischem this, geschrieben zum Beispiel als const add = (a, b) => a + b.',
    'A compact function syntax with lexical this, for example const add = (a, b) => a + b.'),
  studyQuestion(39, 2, topics.javascript,
    'Was bedeutet Scope in JavaScript?',
    'What does scope mean in JavaScript?',
    'Der Bereich, in dem eine Variable oder Funktion sichtbar und zugänglich ist.',
    'The region in which a variable or function is visible and accessible.'),

  studyQuestion(40, 2, topics.javascript,
    'Was bedeutet Hoisting in JavaScript?',
    'What does hoisting mean in JavaScript?',
    'Deklarationen werden bei der Verarbeitung ihres Scopes vor der Ausführung registriert; ihr tatsächliches Verhalten hängt von var, let, const oder function ab.',
    'Declarations are registered when their scope is processed before execution; the exact behavior depends on var, let, const, or function.'),
  studyQuestion(41, 3, topics.javascript,
    'Was liefert Object.keys()?',
    'What does Object.keys() return?',
    'Ein Array mit den eigenen aufzählbaren Property-Namen eines Objekts.',
    'An array containing an object’s own enumerable property names.'),
  studyQuestion(42, 3, topics.javascript,
    'Was macht Optional Chaining mit ?.',
    'What does optional chaining with ?. do?',
    'Es greift sicher auf verschachtelte Properties oder Methoden zu und liefert undefined, wenn ein früher Teil null oder undefined ist.',
    'It safely accesses nested properties or methods and returns undefined if an earlier part is null or undefined.'),
  studyQuestion(43, 3, topics.browser,
    'Was macht addEventListener()?',
    'What does addEventListener() do?',
    'Es registriert eine Funktion, die ausgeführt wird, wenn ein bestimmtes Event auf einem Ziel eintritt.',
    'It registers a function to run when a specific event occurs on a target.'),
  studyQuestion(44, 3, topics.browser,
    'Was ist localStorage?',
    'What is localStorage?',
    'Ein Browser-Speicher für String-Daten, die für dieselbe Origin auch nach dem Schließen des Browsers erhalten bleiben.',
    'Browser storage for string data that remains available to the same origin after the browser is closed.'),
  studyQuestion(45, 3, topics.browser,
    'Was ist sessionStorage?',
    'What is sessionStorage?',
    'Ein Browser-Speicher pro Tab beziehungsweise Sitzung, der beim Schließen des Tabs gelöscht wird.',
    'Browser storage scoped to a tab or session that is cleared when the tab is closed.'),
  studyQuestion(46, 3, topics.browser,
    'Was sind Cookies?',
    'What are cookies?',
    'Kleine Schlüssel-Wert-Daten, die der Browser speichert und bei passenden HTTP-Requests an den Server mitsenden kann.',
    'Small key-value data stored by the browser that can be sent to the server with matching HTTP requests.'),
  studyQuestion(47, 3, topics.http,
    'Was ist CORS?',
    'What is CORS?',
    'Ein Browser-Sicherheitsmechanismus, bei dem Server über HTTP-Header erlaubte Cross-Origin-Zugriffe festlegen.',
    'A browser security mechanism in which servers use HTTP headers to allow selected cross-origin access.'),
  studyQuestion(48, 3, topics.browser,
    'Wie verbessert man die Performance einer Webseite?',
    'How can website performance be improved?',
    'Durch kleinere Assets, weniger JavaScript, Caching, Lazy Loading, effizientes Rendering und das Messen realer Engpässe.',
    'By reducing asset size and JavaScript, using caching and lazy loading, rendering efficiently, and measuring real bottlenecks.'),
  studyQuestion(49, 3, topics.browser,
    'Was bedeutet Rendering im Browser?',
    'What does rendering mean in the browser?',
    'Der Prozess, bei dem DOM und CSSOM zu Layout, Pixeln und der sichtbaren Webseite verarbeitet werden.',
    'The process of turning the DOM and CSSOM into layout, pixels, and the visible page.'),
  studyQuestion(50, 3, topics.tooling,
    'Was ist npm?',
    'What is npm?',
    'Ein Paketmanager und Registry-Ökosystem für JavaScript-Abhängigkeiten und Projektskripte.',
    'A package manager and registry ecosystem for JavaScript dependencies and project scripts.'),
  studyQuestion(51, 3, topics.tooling,
    'Was passiert in einem Frontend-Build-Prozess?',
    'What happens during a frontend build process?',
    'Quellcode und Assets werden geprüft, transformiert, gebündelt und für die Auslieferung optimiert.',
    'Source code and assets are checked, transformed, bundled, and optimized for delivery.'),
  studyQuestion(52, 3, topics.tooling,
    'Was bedeutet Deployment?',
    'What does deployment mean?',
    'Eine gebaute Anwendung wird in eine Umgebung veröffentlicht, in der Nutzer sie erreichen können.',
    'A built application is published to an environment where users can access it.'),

  studyQuestion(53, 3, topics.react,
    'Was ist JSX?',
    'What is JSX?',
    'Eine JavaScript-Syntaxerweiterung, mit der UI-Strukturen ähnlich wie HTML im Code beschrieben werden.',
    'A JavaScript syntax extension for describing UI structures in a form similar to HTML.'),
  studyQuestion(54, 3, topics.react,
    'Warum brauchen Listenelemente in React einen key?',
    'Why do list items in React need a key?',
    'Ein stabiler key hilft React, Elemente zwischen Renderings korrekt zuzuordnen und effizient zu aktualisieren.',
    'A stable key helps React match items between renders and update them efficiently.'),
  studyQuestion(55, 3, topics.react,
    'Was ist Conditional Rendering?',
    'What is conditional rendering?',
    'Das Anzeigen unterschiedlicher UI abhängig von Zustand oder Bedingungen, etwa mit if, && oder dem ternären Operator.',
    'Showing different UI based on state or conditions, using if, &&, or the ternary operator.'),
  studyQuestion(56, 3, topics.react,
    'Wozu dient useRef?',
    'What is useRef used for?',
    'Zum Speichern eines veränderlichen Werts ohne Re-Render oder zum Referenzieren eines DOM-Elements.',
    'To store a mutable value without re-rendering or to reference a DOM element.'),
  studyQuestion(57, 3, topics.react,
    'Wozu dient React Context?',
    'What is React Context used for?',
    'Zum Bereitstellen gemeinsamer Werte für einen Komponentenbaum, ohne Props durch jede Zwischenebene weiterzureichen.',
    'To provide shared values to a component tree without passing props through every intermediate level.'),
  studyQuestion(58, 3, topics.http,
    'Was macht fetch()?',
    'What does fetch() do?',
    'fetch() startet einen HTTP-Request und liefert ein Promise mit einem Response-Objekt.',
    'fetch() starts an HTTP request and returns a Promise containing a Response object.'),
  studyQuestion(59, 3, topics.react,
    'Was ist clientseitiges Routing?',
    'What is client-side routing?',
    'Die URL und Ansicht wechseln im Browser, ohne bei jeder Navigation ein vollständiges neues HTML-Dokument zu laden.',
    'The URL and view change in the browser without loading a complete new HTML document for every navigation.'),
  studyQuestion(60, 3, topics.architecture,
    'Welche Arten von Tests sind in Webanwendungen wichtig?',
    'Which kinds of tests are important in web applications?',
    'Unit-Tests prüfen kleine Einheiten, Integrationstests ihr Zusammenspiel und End-to-End-Tests vollständige Nutzerabläufe.',
    'Unit tests check small units, integration tests check how they work together, and end-to-end tests check complete user flows.'),
  studyQuestion(61, 4, topics.architecture,
    'Was bedeutet Single Source of Truth?',
    'What does single source of truth mean?',
    'Eine Information wird an einer maßgeblichen Stelle verwaltet, statt in mehreren unabhängigen Kopien.',
    'A piece of information is managed in one authoritative place instead of several independent copies.'),
  studyQuestion(62, 4, topics.architecture,
    'Was zeichnet eine gute Projektordnerstruktur aus?',
    'What makes a good project folder structure?',
    'Sie gruppiert zusammengehörige Dateien nachvollziehbar, hält Verantwortlichkeiten klar und bleibt bei wachsendem Projekt auffindbar.',
    'It groups related files predictably, keeps responsibilities clear, and remains navigable as the project grows.'),
  studyQuestion(63, 4, topics.security,
    'Was ist Authentifizierung?',
    'What is authentication?',
    'Der Prozess, mit dem überprüft wird, wer ein Nutzer oder eine Anwendung ist.',
    'The process of verifying who a user or application is.'),
  studyQuestion(64, 4, topics.security,
    'Was ist Multi-Faktor-Authentifizierung (MFA)?',
    'What is multi-factor authentication (MFA)?',
    'Eine Anmeldung mit mindestens zwei unterschiedlichen Nachweisarten, etwa Passwort und Einmalcode.',
    'A sign-in that requires at least two different types of proof, such as a password and a one-time code.'),
  studyQuestion(65, 4, topics.http,
    'Wie läuft ein typischer Request-Response-Zyklus ab?',
    'How does a typical request-response cycle work?',
    'Ein Client sendet einen Request, der Server verarbeitet ihn und sendet eine Response mit Status, Headern und optionalen Daten zurück.',
    'A client sends a request, the server processes it, and returns a response with a status, headers, and optional data.'),
studyQuestion(66, 4, text('JavaScript', 'JavaScript'),
  'Welche Aussagen über Scope sind korrekt?',
  'Which statements about scope are correct?',
  'let und const sind block-scoped | var ist function-scoped | Scope beschreibt, wo Variablen sichtbar/verwendbar sind',
  'let and const are block-scoped | var is function-scoped | scope describes where variables are visible and usable'),
studyQuestion(67, 4, text('JavaScript', 'JavaScript'),
  'Welche Aussagen über Hoisting sind korrekt?',
  'Which statements about hoisting are correct?',
  'Funktionsdeklarationen werden oft vor ihrer Position nutzbar (hoisted) | var-Deklarationen werden „hochgezogen“, aber initialisiert erst später',
  'Function declarations are often usable before their position (hoisted) | var declarations are hoisted but initialized later'),
studyQuestion(68, 4, text('JavaScript', 'JavaScript'),
  'Welche Aussagen über Object.keys() sind korrekt?',
  'Which statements about Object.keys() are correct?',
  'Es liefert ein Array der eigenen (enumerable) Schlüsselnamen eines Objekts | Es ist nützlich, um über Properties zu iterieren',
  'It returns an array of an object’s own enumerable key names | It is useful for iterating over properties'),
studyQuestion(69, 4, text('JavaScript', 'JavaScript'),
  'Welche Aussagen zu Optional Chaining (?.) sind korrekt?',
  'Which statements about optional chaining (?.) are correct?',
  'Es verhindert Fehler beim Zugriff auf tief verschachtelte Properties, wenn etwas undefined/null ist | Es kann auch bei Funktionsaufrufen genutzt werden (z. B. obj.fn?.())',
  'It prevents errors when accessing deeply nested properties if something is undefined or null | It can also be used for function calls (e.g. obj.fn?.())'),
studyQuestion(70, 4, text('JavaScript', 'JavaScript'),
  'Welche Aussagen zu Event Listenern sind korrekt?',
  'Which statements about event listeners are correct?',
  'addEventListener("click", ...) reagiert auf Klicks | Events sind z.B. Klicks, Tastatur-Eingaben oder Submit | Man kann mit preventDefault() Standardverhalten verhindern (z.B. bei Formularen)',
  'addEventListener("click", ...) reacts to clicks | events include clicks, keyboard input, or submit | preventDefault() can stop default behavior (e.g. on forms)'),
studyQuestion(71, 4, text('Web APIs', 'Web APIs'),
  'Welche Aussagen über localStorage sind korrekt?',
  'Which statements about localStorage are correct?',
  'Daten bleiben in der Regel nach einem Reload bestehen | Es speichert Strings (Objekte müssen oft per JSON.stringify gespeichert werden) | localStorage ist pro Origin (Domain/Protokoll/Port) getrennt',
  'Data usually persists after a reload | it stores strings (objects often need to be saved via JSON.stringify) | localStorage is separated by origin (domain/protocol/port)'),
studyQuestion(72, 4, text('Web APIs', 'Web APIs'),
  'Welche Aussagen über sessionStorage sind korrekt?',
  'Which statements about sessionStorage are correct?',
  'Daten sind typischerweise nur für den Tab/Session gültig | Es speichert Strings ähnlich wie localStorage | Es ist pro Origin getrennt',
  'Data is typically valid only for the tab/session | it stores strings similar to localStorage | it is separated by origin'),
studyQuestion(73, 4, text('HTTP', 'HTTP'),
  'Welche Aussagen über Cookies sind korrekt?',
  'Which statements about cookies are correct?',
  'Cookies können automatisch bei Requests an die Domain gesendet werden (je nach Einstellungen) | HttpOnly-Cookies sind typischerweise nicht per JavaScript auslesbar',
  'Cookies can be automatically sent with requests to the domain (depending on settings) | HttpOnly cookies are typically not readable by JavaScript'),
studyQuestion(74, 4, text('HTTP', 'HTTP'),
  'Welche Aussagen zu CORS sind korrekt?',
  'Which statements about CORS are correct?',
  'CORS regelt, ob eine Website Ressourcen von einer anderen Origin abrufen darf | CORS ist ein Browser-Sicherheitsmechanismus (nicht „Server blockiert“, sondern Browser setzt Regeln um)',
  'CORS determines whether a website can fetch resources from another origin | CORS is a browser security mechanism (not the server blocking, but the browser enforcing rules)'),
studyQuestion(75, 4, text('Performance', 'Performance'),
  'Welche Maßnahmen verbessern oft Web-Performance?',
  'Which measures often improve web performance?',
  'Bilder optimieren (Größe/Format) und lazy loading nutzen | Unnötiges JavaScript reduzieren (Bundle kleiner halten) | Caching nutzen (Browser/Server), wo sinnvoll',
  'Optimize images (size/format) and use lazy loading | reduce unnecessary JavaScript (keep the bundle smaller) | use caching (browser/server) where it makes sense'),
studyQuestion(76, 4, text('Performance', 'Performance'),
  'Welche Aussagen über Rendering sind korrekt?',
  'Which statements about rendering are correct?',
  'Der Browser parst HTML und baut daraus das DOM | CSS beeinflusst Layout und Paint | JavaScript kann das DOM verändern und dadurch Reflows/Repaints auslösen',
  'The browser parses HTML and builds the DOM | CSS affects layout and paint | JavaScript can change the DOM and cause reflows/repaints'),
studyQuestion(77, 4, text('Tooling', 'Tooling'),
  'Welche Aussagen über npm sind korrekt?',
  'Which statements about npm are correct?',
  'npm verwaltet JavaScript-Pakete/Dependencies | package.json beschreibt u.a. Abhängigkeiten und Scripts | npm install installiert Abhängigkeiten (typischerweise in node_modules)',
  'npm manages JavaScript packages/dependencies | package.json describes dependencies and scripts | npm install installs dependencies (typically into node_modules)'),
studyQuestion(78, 4, text('Tooling', 'Tooling'),
  'Was macht npm run build typischerweise in einem Frontend-Projekt?',
  'What does npm run build typically do in a frontend project?',
  'Es erstellt eine Produktionsversion (optimiert) der App | Es erzeugt oft einen Output-Ordner (z.B. dist oder build)',
  'It creates an optimized production version of the app | it often outputs a folder like dist or build'),
studyQuestion(79, 4, text('Deployment', 'Deployment'),
  'Was bedeutet Deployment im Web-Kontext typischerweise?',
  'What does deployment typically mean in a web context?',
  'Eine App im Internet/auf einem Server bereitstellen | Eine App für Nutzer zugänglich machen',
  'Deploy an app to the internet/on a server | make an app available to users'),
studyQuestion(80, 4, text('React', 'React'),
  'Welche Aussagen über JSX sind korrekt?',
  'Which statements about JSX are correct?',
  'JSX ist eine Syntax-Erweiterung, um UI ähnlich wie HTML zu beschreiben | In JSX kann man JavaScript-Ausdrücke mit {} einbetten',
  'JSX is a syntax extension for describing UI similar to HTML | in JSX you can embed JavaScript expressions with {}'),
studyQuestion(81, 5, text('React', 'React'),
  'Was ist beim Rendern von Listen in React wichtig?',
  'What is important when rendering lists in React?',
  'Man nutzt häufig map(), um aus Daten JSX-Elemente zu erzeugen | Jedes Listenelement sollte einen stabilen key erhalten',
  'You often use map() to turn data into JSX elements | each list item should get a stable key'),
studyQuestion(82, 5, text('React', 'React'),
  'Welche Aussagen über keys in React sind korrekt?',
  'Which statements about keys in React are correct?',
  'Keys helfen React, Elemente zwischen Renders wiederzuerkennen | Stabile Keys verbessern oft Performance und verhindern UI-Bugs bei Listen | Keys müssen nur innerhalb einer Liste eindeutig sein',
  'Keys help React recognize elements between renders | stable keys often improve performance and prevent UI bugs in lists | keys only need to be unique within a list'),
studyQuestion(83, 5, text('React', 'React'),
  'Welche Aussagen über Conditional Rendering in JSX sind korrekt?',
  'Which statements about conditional rendering in JSX are correct?',
  'Mit && kann man etwas nur rendern, wenn links truthy ist | Mit dem ternären Operator kann man zwischen zwei UI-Varianten wählen | Man kann auch früh returnen (early return), um Bedingungen abzubilden',
  'With && you can render something only if the left side is truthy | with the ternary operator you can choose between two UI variants | you can also return early to represent conditions'),
studyQuestion(84, 5, text('React Hooks', 'React Hooks'),
  'Welche Aussagen über useState sind korrekt?',
  'Which statements about useState are correct?',
  'useState gibt einen aktuellen Wert und eine Setter-Funktion zurück | Der Setter triggert typischerweise einen Re-Render | useState kann Initialwerte als Funktion erhalten (lazy init)',
  'useState returns a current value and a setter function | the setter typically triggers a re-render | useState can accept initial values as a function (lazy init)'),
studyQuestion(85, 5, text('React Hooks', 'React Hooks'),
  'Welche Aussagen über das Dependency Array in useEffect sind korrekt?',
  'Which statements about the dependency array in useEffect are correct?',
  'Es steuert, wann der Effekt erneut ausgeführt wird | Ein leeres Array bedeutet: Effekt läuft nur einmal nach dem ersten Render (typisch) | Ohne Array läuft der Effekt nach jedem Render',
  'It controls when the effect runs again | an empty array means the effect runs only once after the first render (typically) | without an array the effect runs after every render'),
studyQuestion(86, 5, text('React Hooks', 'React Hooks'),
  'Welche Aussagen über useRef sind korrekt?',
  'Which statements about useRef are correct?',
  'useRef kann eine mutable Referenz speichern, ohne Re-Renders auszulösen | useRef eignet sich u.a. für DOM-Zugriff (z.B. Input fokussieren)',
  'useRef can store a mutable reference without triggering re-renders | useRef is useful for DOM access, such as focusing an input'),
studyQuestion(87, 5, text('React', 'React'),
  'Was bedeutet „State anheben“ (lifting state up)?',
  'What does lifting state up mean?',
  'State in eine übergeordnete Komponente verschieben, damit mehrere Kinder ihn nutzen können',
  'Move state into a parent component so multiple children can use it'),
studyQuestion(88, 5, text('React', 'React'),
  'Welche Aussagen über children-Props sind korrekt?',
  'Which statements about children props are correct?',
  'children enthält Inhalte, die zwischen den Component-Tags stehen | children wird genutzt, um Komponenten „komponierbar“ zu machen | children ist eine Standard-Prop in React',
  'children contains content placed between component tags | children is used to make components composable | children is a standard React prop in React'),
studyQuestion(89, 5, text('React', 'React'),
  'Welche Aussagen über React Context sind korrekt?',
  'Which statements about React Context are correct?',
  'Context hilft, Daten „globaler“ verfügbar zu machen, ohne Props durch viele Ebenen zu reichen | Man greift häufig über useContext() auf Context zu',
  'Context helps make data more widely available without passing props through many levels | you often use useContext() to access context'),
studyQuestion(90, 5, text('React', 'React'),
  'Welche Aussagen über fetch in React sind korrekt?',
  'Which statements about fetch in React are correct?',
  'fetch wird genutzt, um Daten vom Server zu laden | API-Aufrufe macht man oft in useEffect, um Nebenwirkungen zu kapseln | fetch liefert typischerweise ein Promise zurück',
  'fetch is used to load data from the server | API calls are often made in useEffect to contain side effects | fetch typically returns a Promise'),
studyQuestion(91, 5, text('React Router', 'React Router'),
  'Welche Aussagen über Client-Side Routing sind korrekt?',
  'Which statements about client-side routing are correct?',
  'Navigation kann ohne vollständigen Seitenreload passieren | Die URL kann sich ändern, obwohl nur eine HTML-Seite geladen wurde | SPAs nutzen oft Client-Side Routing',
  'Navigation can happen without a full page reload | the URL can change even though only one HTML page was loaded | SPAs often use client-side routing'),
studyQuestion(92, 5, text('React Router', 'React Router'),
  'Wozu dient eine Catch-All Route (z.B. /*) typischerweise?',
  'What is a catch-all route (e.g. /*) typically used for?',
  'Sie fängt unbekannte Pfade ab | Sie zeigt oft eine NotFound/404-Komponente | Sie matcht häufig erst, wenn keine andere Route passt',
  'It catches unknown paths | it often shows a NotFound/404 component | it usually matches only when no other route fits'),
studyQuestion(93, 5, text('React Performance', 'React Performance'),
  'Welche Aussagen über React.memo sind korrekt?',
  'Which statements about React.memo are correct?',
  'React.memo kann Re-Renders vermeiden, wenn Props unverändert sind | React.memo ist eine Optimierung und nicht immer nötig',
  'React.memo can avoid re-renders when props are unchanged | React.memo is an optimization and not always necessary'),
studyQuestion(94, 5, text('React Performance', 'React Performance'),
  'Warum können anonyme Funktionen in JSX manchmal problematisch sein?',
  'Why can anonymous functions in JSX sometimes be problematic?',
  'Sie können bei jedem Render eine neue Referenz erzeugen | Das kann unnötige Re-Renders in Child-Komponenten verursachen | Sie machen Code manchmal schwerer lesbar',
  'They can create a new reference on every render | that can cause unnecessary re-renders in child components | they can make code harder to read'),
studyQuestion(95, 5, text('Testing', 'Testing'),
  'Welche Aussagen über Unit-Tests sind korrekt?',
  'Which statements about unit tests are correct?',
  'Unit-Tests testen eine kleine Einheit (z.B. Funktion/Komponente) isoliert | Unit-Tests helfen Fehler früh zu erkennen',
  'Unit tests test a small unit (e.g. a function or component) in isolation | unit tests help catch errors early'),
studyQuestion(96, 5, text('Testing', 'Testing'),
  'Welche Aussagen über das Ziel von Testing sind korrekt?',
  'Which statements about the goal of testing are correct?',
  'Fehler früh erkennen und Regressionen vermeiden | Vertrauen in Änderungen erhöhen',
  'Catch errors early and avoid regressions | increase confidence in changes'),
studyQuestion(97, 5, text('Architecture', 'Architecture'),
  'Welche Aussagen über „Single Source of Truth“ sind korrekt?',
  'Which statements about single source of truth are correct?',
  'Es bedeutet, dass Daten/Zustand eine eindeutige, verlässliche Quelle haben sollen | Es kann helfen, Inkonsistenzen zu vermeiden',
  'It means data/state should have one authoritative, reliable source | it can help avoid inconsistencies'),
studyQuestion(98, 5, text('Architecture', 'Architecture'),
  'Warum ist eine saubere Ordnerstruktur in Projekten oft wichtig?',
  'Why is a clean folder structure often important in projects?',
  'Bessere Wartbarkeit und Orientierung | Bessere Teamarbeit (Konventionen, Auffindbarkeit) | Reduziert Merge-Konflikte häufig indirekt',
  'Better maintainability and navigation | better team collaboration (conventions, discoverability) | often indirectly reduces merge conflicts'),
studyQuestion(99, 5, text('Security', 'Security'),
  'Welche Aussagen über sichere Passwörter/Authentifizierung sind korrekt?',
  'Which statements about secure passwords/authentication are correct?',
  'Passwörter sollten niemals im Klartext gespeichert werden | HTTPS hilft, Daten auf dem Transportweg zu schützen | Multi-Factor Authentication (MFA) kann Sicherheit erhöhen',
  'Passwords should never be stored in plaintext | HTTPS helps protect data in transit | multi-factor authentication (MFA) can increase security'),
studyQuestion(100, 5, text('Web Basics', 'Web Basics'),
  'Welche Aussagen über den Ablauf eines Webseitenaufrufs sind korrekt?',
  'Which statements about the sequence of a website request are correct?',
  'Der Browser sendet eine Anfrage (Request) und erhält eine Antwort (Response) | Der Browser rendert die erhaltenen Ressourcen (HTML/CSS/JS) zur Darstellung | Zusätzliche Ressourcen (CSS/JS/Bilder) werden oft separat nachgeladen',
  'The browser sends a request and receives a response | the browser renders the received resources (HTML/CSS/JS) to display the page | additional resources (CSS/JS/images) are often loaded separately afterward'),
]


export const getNeckGroupQuestions = (groupId) =>
  neckQuestions.filter((item) => item.group === Number(groupId))

export const getNeckQuestionById = (id) =>
  neckQuestions.find((item) => item.id === id)